service: riversafe

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-2

Custom:
  pythonRequirements:
    dockerizepip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /users/create
          method: get

plugins:
  - serverless-python-requirements
