service: riversafe

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-2

Custom:
  pythonRequirements:
    dockerizepip: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /users/create
          method: get

plugins:
  - serverless-python-requirements
